ChimeraTK/ApplicationCore

include/DeviceModule.h
src/Application.cc
src/DeviceModule.cc
src/ExceptionHandlingDecorator.cc

Remove DeviceModule::writeOnOpen

---

include/Application.h
include/VariableNetworkModuleGraphDumpingVisitor.h
src/Application.cc
src/VariableNetworkModuleGraphDumpingVisitor.cc

This generates graphviz code to visualise the connections between modules

add Application::dumpModuleConnectionGraph()

---

src/DeviceModule.cc

fix for API changes in DeviceAccess (RegisterCatalogue)

---

include/Application.h
src/Application.cc

Simply add timeout to acquiring the testable mode lock and print an error message with the last thread which successfully obtained the thread. Finally throw an exception to help debugging.

TestableMode: detect deadlocks and print culprit

---

.clang-format
.gitignore

- added helper macros for (boost) python bindings
- config generator: fix not copying TestFacility from scripts project to build directory
- Add work around for broken DOOCS pkg-config files breaking linkage
- Make the coverage script build-system agnostic
- project-template: FindDOOCS now links clientlib first
- project-template: link against tine explicitly
- doc: Set -dNOSAFER environment for ghostscript
- file GLOB with symlinks for settings file
- project-template: update Doxyfile for doxygen version of Ubuntu 20.04
- Consolidate coverage options
- Ignore eclipse python project file.
- project-template: update clang-format (ReflowComments)

update project template

---

include/ApplicationCore.h
include/TestFacility.h
include/VoidAccessor.h
src/Application.cc

The VoidAccessor comes along with the convenience classes VoidInput and VoidOutput,
and the TestFacility function getVoid()

Add VoidAccessor

---

Modules/include/Logging.h
Modules/src/Logging.cc

Zenker patch 1

---

CMakeLists.txt
include/TriggerFanOut.h

- fix code formatting
- enable coding style test

Enable coding style check (+fix formatting)

---

Modules/include/Logging.h
Modules/include/ServerHistory.h
Modules/src/Logging.cc
Modules/src/ServerHistory.cc
tests/executables_src/testHistory.cc

License information was added to all file. 
Correct the contributing institute for HZDR contributions.

Use HZDR identifier for HZDR contributions.

---

src/ExceptionHandlingDecorator.cc
tests/executables_src/testExceptionHandling.cc

- fix typos in comment, remove debug output
- add test of exception handling with readAny

test exception handling readany

---

Modules/include/StatusWithMessage.h
Modules/src/StatusWithMessage.cc

owner type should be VariableGroup, so we can put StatusWithMessageInput into VariableGroup

fix: StatusWithMessageInput owner type

---

Modules/src/StatusAggregator.cc
include/Application.h
include/MetaDataPropagatingRegisterDecorator.h
include/Model.h
include/VariableNetworkNode.h
src/MetaDataPropagatingRegisterDecorator.cc
tests/executables_src/testBidirectionalVariables.cc
tests/executables_src/testPropagateDataFaultFlag.cc

- **fix: Ignore data validity through return channels**
- **chore: Minor linter fixes**

feat: Better data validity propagation for return channels

---

src/ConnectionMaker.cc

Sorry, the diff is a bit hard to read, I just added a try-catch-block to print additional information before re-throwing...

feat: improve diagnostics for connection errors

---

src/CircularDependencyDetector.cc

CircularDependencyDetector was running into infinite recursion (causing stack overflow) in a situation of two Modules which are both waiting on each other for initial values

fix: CircularDependencyDetector recursion

---

Modules/src/ConfigReader.cc
Modules/src/StatusAggregator.cc
include/InversionOfControlAccessor.h
include/Model.h
include/TestableMode.h
include/VariableNetworkNode.h
src/DeviceManager.cc
src/Model.cc
src/Module.cc
src/TestableMode.cc
src/VariableNetworkNode.cc
tests/executables_src/testInitialValueSpecD8.cc
tests/executables_src/testUserInputValidator.cc

I recommend review by commit...

Fix warnings

---

tests/executables_src/testDataValidityPropagation.cc

See:
https://redmine.msktools.desy.de/issues/8606

tests: move DataValidity test to DeviceAccess

---

include/EntityOwner.h
include/InversionOfControlAccessor.h
include/Module.h
tests/CMakeLists.txt
tests/executables_src/manual/testConnectedDestructionRunner.cc
tests/executables_src/testAppModuleConnections.cc
tests/executables_src/testConnectedDestruction.cc

fix: Disallow move/delete of connected variables

---

include/InversionOfControlAccessor.h
include/Utilities.h
src/Module.cc
src/Utilities.cc
tests/executables_src/testModules.cc

fix: more detailed control for slashes in names

---

Modules/src/StatusAggregator.cc

Accessing the model in the ApplicationModule's main loop is not thread safe.

fix: race condition

---

include/TestableMode.h
src/TestableMode.cc

This reverts commit 6079438dd370c3b9513b45e48549040cc83b3148 and instead adds another workaround.
The original work around does not work properly, probably because it is very slow. Tests are stalling (some spuriously, some always).
The new work around uses an additional mutex which is not "timed" so TSAN properly recognises it. It will be only locked after the timed mutex has been locked successfully, so that it will always succeed in locking immediately (without blocking). This should add minimal overhead while fixing the TSAN false positive.

fix: use alternative workaround for TSAN false positive

---

Modules/src/UserInputValidator.cc
Python/bindings/include/PyTransferElement.h
Python/bindings/include/PyVoidAccessor.h
Python/bindings/src/PyScalarAccessor.cc
Python/bindings/src/PyVoidAccessor.cc
Python/bindings/src/PythonBindings.cc

- Add ChimeraTK::Boolean
- Add missing VoidInput and VoidOutput
- Some unrelated fix in the UserInputValidator I found while trying to bind that

Misc fixes for the python bindings

---

CMakeLists.txt

This PR bumps the version to 04.03.01

chore: Bump version to 04.03.01

---

src/ConnectionMaker.cc
tests/executables_src/testReverseRecovery.cc

- **feat: Also log unmapped optimisation**
- **fix: Handle special case of promoting WO consumer**

Fix: Reverse recovery with WO consumer

---

CMakeLists.txt

This PR bumps the version to 04.05.01

chore: Bump version to 04.05.01
