ChimeraTK/ApplicationCore

- CMakeLists.txt
- Modules/include/Logging.h
- Modules/src/Logging.cc
- tests/executables_src/testLogging.cc
Fix:
- problem in the logging module, which lead to a wrong message level being assigned to a message 
Feature:
- add option to disable building tests to CMake
- add option to disable building MicroDAQ to CMake (see #62)
> Fix logging

- Modules/include/Logging.h
- Modules/src/Logging.cc
My valgrind says now its fine and #114 is fixed.
Implementing #115 was not so easy, since the TransferElementID is not known when the ScalarPushInput object is created. Now I fill the corresponging map in the mainLoop function before the while loop.
> Fix #114 and #115

- doc/spec_dataValidityPropagation.md
- Added requirement that receivers are faulty on construction (1.8)
- Clarified that validity can be set by the user code in 2.1.5
> Set specification version to V1.0RC1

- doc/spec_exceptionHandling.dox
- src/DeviceModule.cc
The previous order was causing actual race conditions, see #173.
> exception handling spec: swap C.3.3.7 and C.3.3.8

- src/Application.cc
If a circular dependency was checked and the dependent module was not
yet in the waitMap, the lock was never released.
> CircularDependencyDetector: Avoid deadlock in registerDependencyWait

- Modules/include/Logging.h
- Modules/src/Logging.cc
- tests/executables_src/testLogging.cc
Now the Logger is a VariableGroup and in the prepare() method an empty
msg is written once. This makes sure the LoggingModule is not waiting
for initial values of Loggers and messages by other Loggers get lost.
> Logger: Fix missing initial value; add automatic registration with the LoggingModule.

- src/DeviceModule.cc
Slashes are not allowed in module names, but the DeviceModule crates a status module using the CDD (or alias) as a name. The slashes are now replaced by underscores.
> fix DeviceModule throws when using CDD containing slashes

- Modules/include/StatusAggregator.h
- Modules/src/StatusAggregator.cc
make getPriority faster by making prio map static and reduce evaluation frequency
with dcm_ctrl_server, Debug mode, CPU load caused by StatusAggregator was about 600 % and is reduced  to about 120% by this small optimization.
> optimization for StatusAggregator

- Modules/include/PeriodicTrigger.h
Without them, the references become invalid in move operations which leads to subsequent segfaults.
> PeriodicTrigger: add missing move constructor/assignment

- src/Application.cc
Sometimes several long running modules in a row might have caused false alarms. So seen in tests of the llrfctrl server with multiple devices (which require some time to open and initialise).
> make testable mode deadlock detection more robust

- Modules/include/StatusAggregator.h
- Modules/src/StatusAggregator.cc
This helps to understand why the aggregated status is how it is, e.g. when not all inputs are accessible through the control system, or when it is unclear which inputs the aggregator has.
> StatusAggregator debugging option

- src/DeviceModule.cc
This fixes together with another change in DeviceAccess the LNM
MathPlugin with push-type variables as parameters.
> do not recover registers with old VersionNumber (cf. #9961)

- cmake/check-coding-style.sh
- cmake/enable_code_style_check.cmake
Enable by adding
include(cmake/enable_code_style_check.cmake)
to the project's CMakeLists.txt
> [project-template] add coding style checker

- Modules/include/Logging.h
- Modules/src/Logging.cc
- tests/executables_src/testLogging.cc
The changes allow to add Loggers in Modules having the same name, which was not possible before. Now the hierarchy is build in the LoggingModule to avoid clashes. 
Connecting the PVs from the LoggingModule to the PVs added by the Logger does not work automatically. 
This needs to be fixed once the tools are available in ChimeraTK. 
A version that implements the automatic connecting version is prepared can be found in the branch wip_improve_logging. 
For now PVs from the LoggingModule are not added to the CS by an findTagAndAppendToModule overload. This is not needed once they are moved to the PVs added by the Logger in the Hierarchy.
> Wip improve logging

- CMakeLists.txt
- include/Model.h
- include/Utilities.h
- src/Application.cc
- src/TestableMode.cc
- src/Utilities.cc
- Use correct of version pthread_setname_np depending on platform.
- Omit -Wl,--export-dynamic flag on macOS.
> Mac OS compatibility (replaces #261)

- CMakeLists.txt
imported target instead of 'pthreads' is more compatible
> cmake threads usage

- example2/CMakeLists.txt
The example2 cannot be built with the current state of the CMakeLists.txt
> Fix: cmakelists for example2

- Modules/include/VersionInfoProvider.h
- Modules/src/StatusWithMessage.cc
- src/Model.cc
The VersionInfoProvider registers with the Application, so we can find the (singleton-like) instance in the Application. If it is destroyed for whatever reason, this instance pointer must be de-registered to prevent use-after-free as well as allow the subsequent creation of another VersionInfoProvider.
> fix: VersionInfoProvider de-registration at destruct

- include/Model.h
- src/Model.cc
ProcessVariableProxy::removeNode() was effectively taking a reference to
a shared pointer as an argument and is removing the same (effective)
shared pointer from a list. This poses a problem if the reference passed
points to the list directly and is the last shared pointer to this
object so it gets freed, because removeNode() is accessing the object
after removing it from the list.
> fix: use after free

- Modules/include/ScriptedInitialisationHandler.h
If a device was only defined by CDD and the CDD contained some sort of hierarchy separator, the unescaped CDD was causing an invalid variable name.
> fix: Escape device name in initialisation handler

- CMakeLists.txt
> CMake Warning (dev) at CMakeLists.txt:1 (PROJECT):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
> style: move min version to top in cmakelists

- CMakeLists.txt
- Modules/src/StatusAggregator.cc
- tests/executables_src/testStatusAggregator.cc
StatusAggregator was aggregating downstream aggregators according to their
input tags instead of the output tags.
> fix: StatusAgggregator

- Modules/include/StatusAccessor.h
- Modules/include/StatusWithMessage.h
- Modules/src/StatusWithMessage.cc
- include/EntityOwner.h
- include/InversionOfControlAccessor.h
- include/MetaDataPropagatingRegisterDecorator.h
- include/VariableNetworkNode.h
- src/EntityOwner.cc
- src/MetaDataPropagatingRegisterDecorator.cc
- src/Model.cc
- src/VariableNetworkNode.cc
- tests/executables_src/testModules.cc
- tests/executables_src/testPropagateDataFaultFlag.cc
- tests/executables_src/testStatusMonitor.cc
most useful with StatusOutputs, where automatic propagation of 'data invalid' status is often not wanted
> feature: data validity propagation configurable via special tag

- tests/executables_src/testAppModuleConnections.cc
- tests/executables_src/testApplication.cc
- tests/executables_src/testBidirectionalVariables.cc
- tests/executables_src/testCircularDependencyFaultyFlags.cc
- tests/executables_src/testConfigReader.cc
- tests/executables_src/testControlSystemAccessors.cc
- tests/executables_src/testDataValidityPropagation.cc
- tests/executables_src/testDeviceAccessors.cc
- tests/executables_src/testDeviceExceptionFlagPropagation.cc
- tests/executables_src/testDeviceInitialisationHandler.cc
- tests/executables_src/testExceptionHandling.cc
- tests/executables_src/testFanoutConnections.cc
- tests/executables_src/testHierarchyModifyingGroup.cc
- tests/executables_src/testIllegalNetworks.cc
- tests/executables_src/testInitialValueSpecD8.cc
- tests/executables_src/testModel.cc
- tests/executables_src/testModules.cc
- tests/executables_src/testOptimiseUnmappedVariables.cc
- tests/executables_src/testPeriodicTrigger.cc
- tests/executables_src/testProcessVariableRecovery.cc
- tests/executables_src/testPropagateDataFaultFlag.cc
- tests/executables_src/testScriptedInitialisationHandler.cc
- tests/executables_src/testStatusAggregator.cc
- tests/executables_src/testStatusMonitor.cc
- tests/executables_src/testTestFacilities.cc
- tests/executables_src/testTestFacility2.cc
- tests/executables_src/testTrigger.cc
- tests/executables_src/testUserInputValidator.cc
- tests/executables_src/testVariableGroup.cc
- tests/executables_src/testVersionPropagation.cc
This helps in two ways:
1. Doxygen is confused if there are multiple class defintions with the
same name, which happens frequently in tests, e.g. "ModuleA"
2. Doxygen shows rather prominently all classes defined in the tests
when viewing the Class List, while the important classes are "hidden"
at first below the ChimeraTK namespace.
> chore/doc: move all tests to namespace to help Doxygen

- Modules/src/ConfigReader.cc
libxml2 will print out a confusing "I/O warning" if we try to open a
non-existant XML file, and the only way to suppress it is marked as
"DON'T USE" so we check beforehand now
> fix: Suppress libxml2 warning for missing config

- Python/bindings/src/PyApplicationModule.cc
- include/ConstantAccessor.h
- include/FanOut.h
- src/ApplicationModule.cc
- src/TriggerFanOut.cc
When terminating the application while poll-type inputs are waiting for initial values from other ApplicationModules, we need to interrupt() those blocking initial-value reads.
This requires a corresponding change in DeviceAccess to allow calling interrupt() without wait_for_new_data.
Note: This requires https://github.com/ChimeraTK/DeviceAccess/pull/456
> fix: terminate application while still waitig for init values

- CMakeLists.txt
- Python/manager/PythonModuleManager.cc
- PyApplicationCore.pyi must not be in versioned directory, so it is found by the IDE
- prepend the versioned directories so old PyApplicationBindings in the system are not found first
- remove debug output
> fix: python paths

- tests/config/deviceInitScript1.bash
- tests/config/deviceInitScript2.bash
- tests/executables_src/testScriptedInitialisationHandler.cc
- Refactor testScriptedInitHandler into small tests, each testing one particular feature.
- Only use text snippets for the tests. Tests for existence of the snippets, not for full text equality. This makes the test robust against stray gcda error messages seen in the script output.
> chore/fix: refactor tests and make them more robust

- include/MetaDataPropagatingRegisterDecorator.h
- include/VariableNetworkNode.h
- src/MetaDataPropagatingRegisterDecorator.cc
- tests/executables_src/testVersionPropagation.cc
to module, via special tag.
Important use case is PushInputWB, since I cannot convert it into PollInput.
> feat: allow turning off version propagation from input

- include/TestableMode.h
- src/TestableMode.cc
This helps debugging, since the thread ID can be compared with e.g. the stack trace of a debugger.
> feat(TestableMode): print thread ID when test stalled

- include/ConnectionMaker.h
- src/ConnectionMaker.cc
- tests/executables_src/testReverseRecovery.cc
This is also necessary if there are no bi-directional consumers in the
net in addition to not having any consumer in the network
> fix: Promote CS consumer to bi-directional

- Modules/include/ConfigReader.h
- Modules/src/ConfigReader.cc
Otherwise we will be left with a message saying "There is a bug in the
application because it did not call shutdown" since the throw will
happen in the Application's constructor, without any means for learning
about the actual error. This is especially annoying with the generic
server.
> feat: Log the parse error

- include/ExceptionHandlingDecorator.h
- include/FanOut.h
- include/RecoveryHelper.h
- include/ReverseRecoveryDecorator.h
- include/ThreadedFanOut.h
- src/ConnectionMaker.cc
- src/ExceptionHandlingDecorator.cc
- src/ReverseRecoveryDecorator.cc
- tests/config/taggedBitRange.xlmap
- tests/config/testTagged.dmap
- tests/executables_src/testReverseRecovery.cc
Fixes various deadlocks with the LNM BitRange accessor, due to calling
read() while already in a read transfer.
Only decorate the write direction (as direct pass-through). For the read
direction, implement a simple async read scheme that can be triggered
from the DeviceManager when required. Also split the
ReverseRecoveryDecorator from the ExceptionHandlingDecorator and just
put the latter on top of the former
> fix: Rework the ReverseRecoveryDecorator
